name: xgb
early_stopping_rounds: 50
num_boost_round: 2000

objective: reg:squarederror
learning_rate: 0.037
gamma: 2.6
max_depth: 8
min_child_weight: 5
subsample: 0.52
colsample_bytree: 1
reg_lambda: 1.63
reg_alpha: 1.5